/*
 * This file is part of Betaflight.
 *
 * Betaflight is free software. You can redistribute this software
 * and/or modify this software under the terms of the GNU General
 * Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later
 * version.
 *
 * Betaflight is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this software.
 *
 * If not, see <http://www.gnu.org/licenses/>.
 */

// AUTO-GENERATED by tools/gen_vcp_ids.py - do not edit by hand.
// Source: https://build.betaflight.com/api/app/devices (serialDevices)
//
// The set of USB VID:PID pairs Betaflight Configurator recognises as FC
// serial devices. Refresh with: python3 tools/gen_vcp_ids.py
#pragma once

#include <stdint.h>

typedef struct {
    uint16_t vid;
    uint16_t pid;
} vcp_usb_id_t;

static const vcp_usb_id_t k_vcp_ids[] = {
    { 0x0403, 0x6001 },
    { 0x0483, 0x3256 },
    { 0x0483, 0x374E },
    { 0x0483, 0x5740 },
    { 0x10C4, 0xEA60 },
    { 0x10C4, 0xEA61 },
    { 0x10C4, 0xEA62 },
    { 0x28E9, 0x018A },
    { 0x2E3C, 0x5740 },
    { 0x314B, 0x5740 },
    { 0x2E8A, 0x0009 },
    { 0x3997, 0x5740 },
};
