#!/usr/bin/env python3
"""Generate the FC VCP USB ID allowlist from the Betaflight build API.

Source of truth: https://build.betaflight.com/api/app/devices  (serialDevices)
This is the same list Betaflight Configurator uses to recognise FC serial
devices, so the host bridge accepts exactly what Configurator would.

Run on demand to refresh main/vcp_ids.generated.h (the build itself uses the
committed header and does not need network access):

    python3 tools/gen_vcp_ids.py
"""

import json
import sys
import urllib.request
from pathlib import Path

API_URL = "https://build.betaflight.com/api/app/devices"
OUT = Path(__file__).resolve().parent.parent / "src" / "main" / "vcp_ids.generated.h"


def fetch(url):
    # The build API rejects the default urllib User-Agent with 403.
    req = urllib.request.Request(url, headers={"User-Agent": "betaflight-host/gen_vcp_ids"})
    with urllib.request.urlopen(req, timeout=20) as r:
        return json.load(r)


def main():
    data = fetch(API_URL)
    devices = data.get("serialDevices", [])
    seen = set()
    rows = []
    for d in devices:
        vid = int(d["vendorId"])
        pid = int(d["productId"])
        if (vid, pid) in seen:
            continue
        seen.add((vid, pid))
        rows.append((vid, pid))

    if not rows:
        sys.exit("error: no serialDevices returned by build API")

    lines = [
        "/*",
        " * This file is part of Betaflight.",
        " *",
        " * Betaflight is free software. You can redistribute this software",
        " * and/or modify this software under the terms of the GNU General",
        " * Public License as published by the Free Software Foundation,",
        " * either version 3 of the License, or (at your option) any later",
        " * version.",
        " *",
        " * Betaflight is distributed in the hope that it will be useful,",
        " * but WITHOUT ANY WARRANTY; without even the implied warranty of",
        " * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.",
        " *",
        " * See the GNU General Public License for more details.",
        " *",
        " * You should have received a copy of the GNU General Public",
        " * License along with this software.",
        " *",
        " * If not, see <http://www.gnu.org/licenses/>.",
        " */",
        "",
        "// AUTO-GENERATED by tools/gen_vcp_ids.py - do not edit by hand.",
        f"// Source: {API_URL} (serialDevices)",
        "//",
        "// The set of USB VID:PID pairs Betaflight Configurator recognises as FC",
        "// serial devices. Refresh with: python3 tools/gen_vcp_ids.py",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "    uint16_t vid;",
        "    uint16_t pid;",
        "} vcp_usb_id_t;",
        "",
        "static const vcp_usb_id_t k_vcp_ids[] = {",
    ]
    for vid, pid in rows:
        lines.append(f"    {{ 0x{vid:04X}, 0x{pid:04X} }},")
    lines.append("};")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(rows)} ids)")


if __name__ == "__main__":
    main()
